### ISSUE TITLE
Deploy command is not executing in correct way

### ISSUE THREAD

**Issue by LikoIlya** [uconomy/lava#1]
Hi, guys!
I very much appreciated your work and try to use `Lava` in everyday work with contracts, but I was stuck in some issues with compiling and then deploying my contracts, so...

I have nested structure of `contracts` folder like
 - `contracts`
    - `main` - that stores main bodies of contacts that I want to compile and deploy. (Multiple contracts included).
    - `types`, `helpers`, `views`, etc. - folders that contain modules of that contacts.
 
When I tried to compile with the default config I saw error of parsing the folders, so I changed my `contractsDirectory` value to 

``` json
{
   ...
   "contractsDirectory": "contracts/main",
   ...
}
```

And contracts compiles successfully.

But when I tried to use the `deploy` command with key `<CONTRACT_NAME>` - contract from ./contracts/main/<CONTRACT_NAME>.ligo, I got 

```
ERROR: Specified contract <CONTRACT_NAME> doesn't exist.
```

I tried to use the `-f` key but saw that it just appends ./contracts to the passed path.

What could you suggest to my problem?

**Comment by andreapizzato** [comment]
Hi @LikoIlya,
maybe the sub-folder structure is not handled properly. We'll do some testing and report back in a few.
