### ISSUE TITLE
Faucet format update 

### ISSUE THREAD

**Issue by der-alter** [uconomy/lava#7]
Hello, there is a problem occurring after the faucet format has been updated

![Screenshot 2022-05-04 at 16-38-57 Tezos Builder Suite](https://user-images.githubusercontent.com/13657413/166705441-d2992c08-629b-47d0-9f4f-c3bf067df8e7.png)

`secret` have been replaced with `activation_code`

see similar taquito changes here https://github.com/ecadlabs/taquito/pull/1388

**Comment by andreapizzato** [comment]
The issue has been fixed in [tezos-builder-suite](https://github.com/uconomy/tezos-builder-suite) and the update has been included in [Lava 1.3.3](https://github.com/uconomy/lava/releases/tag/1.3.3)
